[versions]
agp = "8.8.0"
kotlin = "1.9.25"
coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.3.0"
appcompat = "1.6.1"
material = "1.9.0"
activity = "1.8.2"
constraintlayout = "2.1.4"
swiperefreshlayout = "1.1.0"
navigationFragmentKtx = "2.7.7"
room = "2.6.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }
room-runtime = { group="androidx.room", name="room-runtime", version.ref="room" }
room-ktx = { group="androidx.room", name="room-ktx", version.ref="room" }
room-compiler = { group = "androidx.room", name="room-compiler", version.ref = "room" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }